[package]
name = "name-variants-py"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
name-variants = { path = "../name-variants-rs" }

[lints]
workspace = true
