
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.name-variants]
audit-as-crates-io = false

[[exemptions.autocfg]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.20.2"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.indoc]]
version = "2.0.7"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.186"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.name-variants]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.4"
criteria = "safe-to-deploy"

[[exemptions.phf]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.phf_generator]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.phf_macros]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.phf_shared]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.106"
criteria = "safe-to-deploy"

[[exemptions.pyo3]]
version = "0.22.6"
criteria = "safe-to-deploy"

[[exemptions.pyo3-build-config]]
version = "0.22.6"
criteria = "safe-to-deploy"

[[exemptions.pyo3-ffi]]
version = "0.22.6"
criteria = "safe-to-deploy"

[[exemptions.pyo3-macros]]
version = "0.22.6"
criteria = "safe-to-deploy"

[[exemptions.pyo3-macros-backend]]
version = "0.22.6"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.45"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.rustversion]]
version = "1.0.22"
criteria = "safe-to-deploy"

[[exemptions.siphasher]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.117"
criteria = "safe-to-deploy"

[[exemptions.target-lexicon]]
version = "0.12.16"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.unindent]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.121"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.121"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.121"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.121"
criteria = "safe-to-deploy"
