"""Chinese given-name romanization variants.

Canonical keys are Simplified Chinese characters.
Variants are romanizations (lowercase, with and without tone marks).

Note: romanizations that conflict with the 15 surname/family-name tables have
been removed so that lookup_key() continues to prefer surname canonicals for
ambiguous strings.  Tonal variants (e.g. míng) are retained where the bare
form (ming) would not conflict.
"""

CHINESE_GIVEN_NAME_VARIANTS: dict[str, list[str]] = {
    # ── Male given names ──────────────────────────────────────────────────────
    "明": ["ming", "míng"],
    "文": ["wén"],
    "伟": ["wěi"],
    "强": ["qiang", "qiáng"],
    "军": ["jūn"],
    "杰": ["jie", "jié"],
    "勇": ["yǒng"],
    "涛": ["tao", "tāo"],
    "志": ["zhi", "zhì"],
    "超": ["chāo"],
    "刚": ["gāng"],
    "磊": ["lěi"],
    "鑫": ["xin", "xīn"],
    "健": ["jian", "jiàn"],
    "博": ["bo", "bó"],
    "辉": ["huī"],
    "浩": ["hào"],
    "飞": ["fēi"],
    "亮": ["liàng"],
    "帅": ["shuai", "shuài"],
    "龙": ["lóng"],
    "武": ["wǔ"],
    "斌": ["bīn"],
    "峰": ["fēng"],
    "海": ["hǎi"],
    "锋": ["fèng"],
    "宇": ["yǔ"],
    "昊": ["háo"],
    "翔": ["xiáng"],
    "凯": ["kai", "kǎi"],
    "晨": ["chén"],
    "泽": ["zé"],
    "轩": ["xuān"],
    "炀": ["yáng"],
    "睿": ["rui", "ruì"],
    "鹏": ["péng"],
    "坤": ["kun", "kūn"],
    "东": ["dōng"],
    "旭": ["xù"],
    # ── Female given names ────────────────────────────────────────────────────
    "芳": ["fāng"],
    "燕": ["yàn"],
    "娟": ["juān"],
    "艳": ["yàn"],
    "霞": ["xia", "xiá"],
    "萍": ["píng"],
    "丽": ["lì"],
    "英": ["yīng"],
    "静": ["jìng"],
    "玲": ["líng"],
    "秀": ["xiu", "xiù"],
    "梅": ["méi"],
    "敏": ["mǐn"],
    "雪": ["xuě"],
    "雅": ["ya", "yǎ"],
    "婷": ["ting", "tíng"],
    "欣": ["xīn"],
    "晶": ["jīng"],
    "慧": ["huì"],
    "薇": ["wēi"],
    "琳": ["lín"],
    "莹": ["yíng"],
    "佳": ["jiā"],
    "倩": ["qiàn"],
    "洁": ["jié"],
    "颖": ["yǐng"],
    "蕾": ["lěi"],
    "璐": ["lù"],
    "嘉": ["jiā"],
    "蓉": ["róng"],
    "珊": ["shān"],
    "琪": ["qi", "qí"],
    "晴": ["qíng"],
    "菊": ["jú"],
    "凤": ["fèng"],
    "兰": ["lán"],
    "红": ["hóng"],
    "春": ["chūn"],
    "桂": ["gui", "guì"],
    "淑": ["shū"],
    "香": ["xiāng"],
    "萱": ["xuān"],
    "彤": ["tóng"],
    "悦": ["yue", "yuè"],
    # ── Gender-neutral ────────────────────────────────────────────────────────
    "华": ["huá"],
    "阳": ["yáng"],
    "洋": ["yáng"],
    "扬": ["yáng"],
    "晓": ["xiǎo"],
    "子": ["zǐ"],
    "天": ["tiān"],
    "心": ["xīn"],
    "云": ["yún"],
    "思": ["sī"],
    "宁": ["níng"],
    "安": ["ān"],
    "乐": ["lè"],
    "诚": ["chéng"],
    "灿": ["can", "càn"],
    "青": ["qīng"],
    "然": ["rán"],
    "奇": ["qi", "qí"],
    "远": ["yuǎn"],
    "畅": ["chàng"],
    "康": ["kāng"],
    "成": ["chéng"],
    "林": ["lín"],
    "建": ["jian", "jiàn"],
    "国": ["guó"],
    "平": ["ping", "píng"],
    "新": ["xīn"],
    "向": ["xiàng"],
    "光": ["guang", "guāng"],
    "利": ["lì"],
    "德": ["dé"],
    "继": ["jì"],
    "仁": ["rén"],
    "义": ["yì"],
    "礼": ["lǐ"],
    "信": ["xin", "xìn"],
    "智": ["zhi", "zhì"],
}
