"""Chinese given-name romanization variants.

Canonical keys are Simplified Chinese characters.
Variants are romanizations (lowercase, with and without tone marks).

Genuine romanization ambiguity is a feature: lookup() returns ALL matching
clusters.  Both bare and tonal pinyin forms are included.
"""

CHINESE_GIVEN_NAME_VARIANTS: dict[str, list[str]] = {
    # ── Male given names ──────────────────────────────────────────────────────
    "明": ["ming", "míng"],
    "文": ["wen", "wén"],
    "伟": ["wei", "wěi"],
    "强": ["qiang", "qiáng"],
    "军": ["jun", "jūn"],
    "杰": ["jie", "jié"],
    "勇": ["yong", "yǒng"],
    "涛": ["tao", "tāo"],
    "志": ["zhi", "zhì"],
    "超": ["chao", "chāo"],
    "刚": ["gang", "gāng"],
    "磊": ["lei", "lěi"],
    "鑫": ["xin", "xīn"],
    "健": ["jian", "jiàn"],
    "博": ["bo", "bó"],
    "辉": ["hui", "huī"],
    "浩": ["hao", "hào"],
    "飞": ["fei", "fēi"],
    "亮": ["liang", "liàng"],
    "帅": ["shuai", "shuài"],
    "龙": ["long", "lóng"],
    "武": ["wu", "wǔ"],
    "斌": ["bin", "bīn"],
    "峰": ["feng", "fēng"],
    "海": ["hǎi"],
    "锋": ["feng", "fèng"],
    "宇": ["yu", "yǔ"],
    "昊": ["hao", "háo"],
    "翔": ["xiang", "xiáng"],
    "凯": ["kai", "kǎi"],
    "晨": ["chen", "chén"],
    "泽": ["ze", "zé"],
    "轩": ["xuan", "xuān"],
    "炀": ["yang", "yáng"],
    "睿": ["rui", "ruì"],
    "鹏": ["peng", "péng"],
    "坤": ["kun", "kūn"],
    "东": ["dong", "dōng"],
    "旭": ["xu", "xù"],
    # ── Female given names ────────────────────────────────────────────────────
    "芳": ["fang", "fāng"],
    "燕": ["yan", "yàn"],
    "娟": ["juan", "juān"],
    "艳": ["yan", "yàn"],
    "霞": ["xia", "xiá"],
    "萍": ["ping", "píng"],
    "丽": ["li", "lì"],
    "英": ["ying", "yīng"],
    "静": ["jing", "jìng"],
    "玲": ["ling", "líng"],
    "秀": ["xiu", "xiù"],
    "梅": ["mei", "méi"],
    "敏": ["min", "mǐn"],
    "雪": ["xue", "xuě"],
    "雅": ["ya", "yǎ"],
    "婷": ["ting", "tíng"],
    "欣": ["xin", "xīn"],
    "晶": ["jing", "jīng"],
    "慧": ["hui", "huì"],
    "薇": ["wei", "wēi"],
    "琳": ["lin", "lín"],
    "莹": ["ying", "yíng"],
    "佳": ["jiā"],
    "倩": ["qian", "qiàn"],
    "洁": ["jié"],
    "颖": ["ying", "yǐng"],
    "蕾": ["lei", "lěi"],
    "璐": ["lu", "lù"],
    "嘉": ["jiā"],
    "蓉": ["rong", "róng"],
    "珊": ["shan", "shān"],
    "琪": ["qi", "qí"],
    "晴": ["qing", "qíng"],
    "菊": ["ju", "jú"],
    "凤": ["feng", "fèng"],
    "兰": ["lan", "lán"],
    "红": ["hong", "hóng"],
    "春": ["chun", "chūn"],
    "桂": ["gui", "guì"],
    "淑": ["shu", "shū"],
    "香": ["xiang", "xiāng"],
    "萱": ["xuan", "xuān"],
    "彤": ["tong", "tóng"],
    "悦": ["yue", "yuè"],
    # ── Gender-neutral ────────────────────────────────────────────────────────
    "华": ["hua", "huá"],
    "阳": ["yang", "yáng"],
    "洋": ["yang", "yáng"],
    "扬": ["yang", "yáng"],
    "晓": ["xiao", "xiǎo"],
    "子": ["zi", "zǐ"],
    "天": ["tian", "tiān"],
    "心": ["xin", "xīn"],
    "云": ["yun", "yún"],
    "思": ["si", "sī"],
    "宁": ["ning", "níng"],
    "安": ["an", "ān"],
    "乐": ["le", "lè"],
    "诚": ["cheng", "chéng"],
    "灿": ["can", "càn"],
    "青": ["qing", "qīng"],
    "然": ["ran", "rán"],
    "奇": ["qi", "qí"],
    "远": ["yuan", "yuǎn"],
    "畅": ["chang", "chàng"],
    "康": ["kang", "kāng"],
    "成": ["cheng", "chéng"],
    "林": ["lin", "lín"],
    "建": ["jian", "jiàn"],
    "国": ["guo", "guó"],
    "平": ["ping", "píng"],
    "新": ["xin", "xīn"],
    "向": ["xiang", "xiàng"],
    "光": ["guang", "guāng"],
    "利": ["li", "lì"],
    "德": ["de", "dé"],
    "继": ["ji", "jì"],
    "仁": ["ren", "rén"],
    "义": ["yi", "yì"],
    "礼": ["li", "lǐ"],
    "信": ["xin", "xìn"],
    "智": ["zhi", "zhì"],
}
