"""Japanese given-name romanization variants.

Canonical keys are kanji (single or compound) or katakana for kana-only names.
Variants are romanizations (lowercase).

Note: romanizations that conflict with the 15 surname/family-name tables have
been removed so that lookup_key() continues to prefer surname canonicals.
The canonical kanji/katakana characters are always reachable via lookup_candidates().
"""

JAPANESE_GIVEN_NAME_VARIANTS: dict[str, list[str]] = {
    # ── Top male given names (kanji) ──────────────────────────────────────────
    "大翔": ["hiroto", "haruto", "yamato"],
    "悠真": ["yuma"],
    "蒼": ["ao", "sou"],
    "湊": ["minato"],
    "律": ["ritsu"],
    "朝陽": ["asahi"],
    "樹": ["itsuki", "ki", "tatsuki"],
    "大和": ["yamato"],
    "颯": ["sou", "hayate"],
    "竜": ["tatsu"],
    "健": ["ken", "takeshi"],
    "誠": ["makoto", "sei"],
    "翔": ["sho", "tsubasa", "kakeru"],
    "豊": ["yutaka", "toyo"],
    "拓": ["taku", "hiroshi"],
    "健太": ["kenta"],
    "雄太": ["yuta"],
    "次郎": ["jiro"],
    "三郎": ["saburo"],
    "太郎": ["taro"],
    "一郎": ["ichiro"],
    "慎": ["makoto"],
    "剛": ["tsuyoshi"],
    "豪": ["takeshi"],
    "進": ["susumu"],
    "徹": ["toru", "tetsu"],
    "浩": ["hiroshi"],
    "弘": ["hiroshi", "hiro"],
    "聡": ["satoshi"],
    "智": ["satoshi", "tomo"],
    "勇": ["isamu"],
    "優": ["masaru"],
    "光": ["hikaru", "mitsu", "kou"],
    "輝": ["hikaru", "teru"],
    "和": ["kazu", "nagi"],
    "剣": ["ken"],
    "龍": ["tatsu"],
    "海": ["kai", "umi"],
    "空": ["sora"],
    "葵": ["aoi"],
    "玲": ["rei"],
    "涼": ["ryo", "ryou"],
    "颯太": ["sota"],
    "大輝": ["daiki", "taiki"],
    "悠": ["hisashi"],
    "京": ["kyo", "miyako"],
    "恵": ["megumi", "kei"],
    "誉": ["homare"],
    # ── Top female given names (kanji) ────────────────────────────────────────
    "陽葵": ["himari", "hinata"],
    "凛": ["rin"],
    "咲": ["saki"],
    "陽菜": ["hina", "haruna"],
    "結菜": ["yuna"],
    "莉子": ["riko"],
    "芽依": ["mei"],
    "愛": ["ai", "megumi"],
    "美咲": ["misaki"],
    "心春": ["koharu"],
    "結衣": ["yui"],
    "桜": ["sakura"],
    "花音": ["kanon"],
    "七海": ["nanami"],
    "彩": ["aya", "sai", "iro"],
    "華": ["hana"],
    "由美": ["yumi"],
    "明美": ["akemi"],
    "真由美": ["mayumi"],
    "亜希": ["aki"],
    "奈々": ["nana"],
    "里奈": ["rina"],
    "美穂": ["miho"],
    "千夏": ["chinatsu"],
    "沙織": ["saori"],
    "佳奈": ["kana"],
    "恵美": ["emi"],
    "奈緒": ["nao"],
    "亜矢": ["aya"],
    # ── Single kanji with common readings ────────────────────────────────────
    "圭": ["kei"],
    "奏": ["kanade"],
    "咲夜": ["sakuya"],
    "杏": ["anzu"],
    "澪": ["mio"],
    "瑠": ["ru"],
    "栞": ["shiori"],
    "朱": ["ake"],
    "夏": ["natsu"],
    "雪": ["yuki", "setsu"],
    "月": ["tsuki", "getsu"],
    "星": ["hoshi", "sei"],
    "風": ["kaze"],
    "花": ["hana"],
    "雅": ["masa", "miyabi"],
    "仁": ["hitoshi"],
    "高太郎": ["kotaro"],
    "五郎": ["goro"],
    "四郎": ["shiro"],
    # ── Katakana entries (kana-only names) ───────────────────────────────────
    "ケンジ": ["kenji"],
    "ユキ": ["yuki"],
    "リョウ": ["ryo"],
    "ハルト": ["haruto"],
    "ソウタ": ["sota"],
    "イツキ": ["itsuki"],
    "アオイ": ["aoi"],
    "コトネ": ["kotone"],
    "ヒカル": ["hikaru"],
    "ナオミ": ["naomi"],
    "マイ": ["mai"],
}
