"""Korean given-name romanization variants.

Canonical keys are Hangul syllables (single or compound).
Variants are romanizations (lowercase).

Note: romanizations that conflict with the 15 surname/family-name tables have
been removed so that lookup_key() continues to prefer surname canonicals.
The canonical Hangul characters are always reachable via lookup_candidates().
"""

KOREAN_GIVEN_NAME_VARIANTS: dict[str, list[str]] = {
    # ── Single-syllable given-name components ─────────────────────────────────
    "재": ["jae"],
    "민": ["min", "meen"],
    "지": ["ji", "jee", "chi"],
    "현": ["hyun", "hyeon"],
    "준": ["joon"],
    "서": ["seo", "suh"],
    "은": ["eun", "un"],
    "수": ["su", "soo"],
    "진": ["jin", "jean"],
    "혜": ["hye", "hae", "hey"],
    "아": ["ah", "a"],
    "영": ["yeong"],
    "미": ["mi", "mee"],
    "나": ["na", "nah"],
    "소": ["so"],
    "윤": ["yoon"],
    "하": ["hah"],
    "유": ["yoo"],
    "세": ["se", "say"],
    "연": ["yeon"],
    "정": ["jeong", "jung"],
    "경": ["kyung", "kyeong", "gyeong"],
    "성": ["seong"],
    "호": ["hoh"],
    "기": ["ki", "gi", "kee"],
    "철": ["cheol", "chul", "chol"],
    "종": ["jong"],
    "원": ["won", "weon"],
    "희": ["hyi"],
    "태": ["tae"],
    "선": ["seon", "sen"],
    "환": ["hwan", "hwon"],
    "우": ["wu"],
    "도": ["doh"],
    "찬": ["chahn"],
    "빈": ["been"],
    "인": ["in", "een"],
    "석": ["seok", "suk", "seck"],
    "한": ["hahn"],
    "상": ["sahng"],
    "오": ["oh"],
    "창": ["chahng"],
    "안": ["ahn"],
    "승": ["seung"],
    "국": ["guk", "kuk"],
    "병": ["byung", "byeong", "byong"],
    "길": ["gil"],
    "광": ["gwang"],
    "봉": ["bong", "bohng"],
    "용": ["ryong"],
    "가": ["ga"],
    "다": ["da"],
    "라": ["ra", "la"],
    "마": ["ma"],
    "바": ["ba"],
    "사": ["sa"],
    "자": ["ja"],
    "차": ["cha", "ca"],
    "파": ["pa"],
    "혁": ["hyuk", "hyeok"],
    # ── Common two-syllable given names ───────────────────────────────────────
    "민준": ["minjun"],
    "서준": ["seojun"],
    "예린": ["yerin"],
    "지우": ["jiu", "jiwo"],
    "지호": ["jiho"],
    "지훈": ["jihun", "jihoon"],
    "수현": ["suhyun", "soohyeon"],
    "예준": ["yejun"],
    "도현": ["dohyun", "dohyeon"],
    "시우": ["siwo"],
}
